# Generated by Django 6.0.1 on 2026-01-21 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_sid', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=50)),
                ('from_number', models.CharField(blank=True, default='', max_length=50)),
                ('to_number', models.CharField(blank=True, default='', max_length=50)),
                ('call_status', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('additional_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallAnsweredEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('additional_data', models.JSONField(default=dict)),
                ('call_sid', models.ForeignKey(db_column='call_sid', on_delete=django.db.models.deletion.CASCADE, to='voiceops.call')),
            ],
            options={
                'db_table': 'call_answered_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallCompletedEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('additional_data', models.JSONField(default=dict)),
                ('call_sid', models.ForeignKey(db_column='call_sid', on_delete=django.db.models.deletion.CASCADE, to='voiceops.call')),
            ],
            options={
                'db_table': 'call_completed_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallInitiatedEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('additional_data', models.JSONField(default=dict)),
                ('call_sid', models.ForeignKey(db_column='call_sid', on_delete=django.db.models.deletion.CASCADE, to='voiceops.call')),
            ],
            options={
                'db_table': 'call_initiated_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallRingingEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('additional_data', models.JSONField(default=dict)),
                ('call_sid', models.ForeignKey(db_column='call_sid', on_delete=django.db.models.deletion.CASCADE, to='voiceops.call')),
            ],
            options={
                'db_table': 'call_ringing_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(default=dict)),
                ('resource_sid', models.ForeignKey(blank=True, db_column='call_sid', null=True, on_delete=django.db.models.deletion.CASCADE, to='voiceops.call')),
            ],
            options={
                'db_table': 'error_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
